development:
  adapter: postgresql
  encoding: unicode
  database: instavent_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: instavent_test
  pool: 5
  username: 
  password: 

production:
  adapter: postgresql
  database: instavent_production
  pool: 5
  timeout: 5000




